name: Run automation tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone edx-app-test repository
      uses: actions/checkout@v2

    # This part here is cloning a second repository
    # While cloning the repository:
    #   - it clones the repo into the given `path`
    #   - it checks out the branch defined at `ref`
    - name: Clone edx-app-test repository
      uses: actions/checkout@v2
      with:
        repository: openedx/edx-app-test

    - name: …
      run: …
