name: "edX Test Suit"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: "edX Unit Tests"
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: "Test iOS 15.2"
            runtime: "iOS-15-2"
            device: "iPhone 8"
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          RUNTIME="${{ matrix.env.runtime }}"
          DEVICE="${{ matrix.env.device }}"
          DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
          RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
          DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
          xcrun simctl boot $DESTINATION_ID
          xcodebuild 
          -workspace edX.xcworkspace 
          -scheme edX -destination $DESTINATION_ID 
          clean build test | xcpretty
  
  snapshot-tests:
    needs: unit-tests
    name: "${{ matrix.env.name }}"
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: "Test iOS 15.2"
            runtime: "iOS-15-2"
            device: "iPhone 8"
            task: "testLTRCurrentOS"
          - name: "Test RTL iOS 15.2"
            runtime: "iOS-15-2"
            device: "iPhone 8"
            task: "testRTLCurrentOS"
          - name: "Test iOS 14.4"
            runtime: "iOS-14-4"
            device: "iPhone 8"
            task: "testLTRPreviousOS"
          - name: "Test RTL iOS 14.4"
            runtime: "iOS-14-4"
            device: "iPhone 8"
            task: "testRTLPreviousOS"
    steps:
    - name: Git checkout
      uses: actions/checkout@v2      
    - name: "Select Xcode 13.2.1"
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
        sudo ln -s /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.4.simruntime
        sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Run tests
      if: always()
      run: |
        TASK="${{ matrix.env.task }}"
        RUNTIME="${{ matrix.env.runtime }}"
        DEVICE="${{ matrix.env.device }}"
        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[^[:alnum:]]/-/g")
        DESTINATION_ID=$(xcrun simctl create "$DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
        xcrun simctl boot $DESTINATION_ID
        ./gradlew -q $TASK | xcpretty -c
      shell: bash